/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as PathfindingRouteImport } from './routes/pathfinding'
import { Route as IndexRouteImport } from './routes/index'

const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const PathfindingRoute = PathfindingRouteImport.update({
  id: '/pathfinding',
  path: '/pathfinding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pathfinding': typeof PathfindingRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pathfinding': typeof PathfindingRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pathfinding': typeof PathfindingRoute
  '/sorting': typeof SortingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pathfinding' | '/sorting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pathfinding' | '/sorting'
  id: '__root__' | '/' | '/pathfinding' | '/sorting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathfindingRoute: typeof PathfindingRoute
  SortingRoute: typeof SortingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathfinding': {
      id: '/pathfinding'
      path: '/pathfinding'
      fullPath: '/pathfinding'
      preLoaderRoute: typeof PathfindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathfindingRoute: PathfindingRoute,
  SortingRoute: SortingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
